jwt:
  secret: this-is-my-very-long-secret-key-for-local-dev-123456
  expiration: 3600000

spring:
  datasource:
    url: jdbc:h2:mem:spring_board;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
